### ISSUE TITLE
CoreFoundation erros in iOS build

### ISSUE THREAD

**Issue by noscript** [lukeweber/webrtc-jingle-client#102]
Hi,

In the current revision I get strange errors from Xcode:

CFURL.h:791:32: Expected ';' after top level declarator
...
CFFileSecurity.h:283:99: Expected function body after function declarator
CoreFoundation.h:92:10: 'CoreFoundation/CFUserNotification.h' file not found

Building for iPhone 6.1 Simulator

**Comment by noscript** [comment]
So it turns out these headers belong to OSX SDK and not iOS. But I have target_os = ['ios'] in my .gclient. What's wrong?

**Comment by noscript** [comment]
Small update. I got a temporary access to the mac with OSX 10.7, and it builds fine there. But on 10.8 I get these CoreFoundation errors.

**Comment by lukeweber** [comment]
I'm on 10.8.4 with xcode 4.6.3 and I'm not seeing any issues. I select voiceclient target and build to ipad or iphone 6.1 simulator. 

To confirm, you did follow the instructions in the readme to generate the xcode project I assume?

If you followed the instructions, the only thing that comes to mind is maybe a partial or bad xcode install, but I'm not an expert in things xcode, so it's just speculation.

**Comment by noscript** [comment]
I reinstalled OSX 10.8.4, now builds fine. Not sure what was the problem, but it wasn't Xcode. I tried previously several Xcode versions, from 4.2 to 4.6 without luck.

**Comment by noscript** [comment]
Figured out the real problem. It was looking for headers in iOS SDK 5.1, while I had only 5.0 installed. The weird thing that I was building for iPhone 5.0 Simulator, so no idea why it was looking for 5.1. I think same happens for SDK 6.x.
