### ISSUE TITLE
Remove config.mk

### ISSUE THREAD

**Issue by jreyes** [lukeweber/webrtc-jingle-client#11]
Since we are going to be passing the stun/turn server information through the api, config.mk and config.mk.fake are not longer needed. Scripts need to be adjusted for this.

**Comment by lukeweber** [comment]
Removed, plus some other's that weren't needed.  

https://github.com/lukeweber/webrtc-jingle-client/commit/168d3c3c75e34fca11af424d675f07a0f21d3860
