### ISSUE TITLE
Jinge voice call ios

### ISSUE THREAD

**Issue by Gowthamindot** [lukeweber/webrtc-jingle-client#125]

**Comment by Gowthamindot** [comment]
Hi
     I have added the jingle coding in ios application.But its coming "Jingle is not connected error".How can i solve this issue.Please do some needful for us.

**Comment by lukeweber** [comment]
It's hard to say with so little information what's going on. I've decided to no longer maintain this project. Please see README.

That being said. There are a few different ways in which you may connect to the xmpp server. The example here could connect to gmail's xmpp although I haven't tested this in a long time. If you wanted to connect to your own xmpp you would need to enable xmpp_compatibility in the defines, but again, it's hard to say.

https://github.com/lukeweber/webrtc-jingle-client/blob/master/client/client_defines.h

**Comment by chathudan** [comment]
if you are using your own server set false to isgtalk in your connection

**Comment by Gowthamindot** [comment]
Hi thanks for yours reply..When am compiling the source code following error occurred.
clang: error: argument unused during compilation: '-msse2' Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1.Please help me to resolve this issue.

**Comment by chathudan** [comment]
follow the README instructions, make sure that you change IOS dev
requirements mention in here
https://github.com/lukeweber/webrtc-jingle-client#ios

**Comment by Gowthamindot** [comment]
Hi
    Its not appearing the two files in source code expat.gyp and  .gclient.Could you please tell me how to generate that files.

**Comment by chathudan** [comment]
those are hidden files

**Comment by Gowthamindot** [comment]
How can i solve that issue?
