### ISSUE TITLE
maven detect number of cores for ndk-build

### ISSUE THREAD

**Issue by lukeweber** [lukeweber/webrtc-jingle-client#23]
In:
webrtc-jingle-client/trunk/pom.xml

On this line the "2" should be replaced with the actual number of cores available on the host build machine.
<ndkBuildAdditionalCommandline>-j2</ndkBuildAdditionalCommandline>

**Comment by jreyes** [comment]
Just modified the android plugin to detect the cores in a host machine, went my build from 30 mins to 4:44 for armeabi and armeabi-v7a with 8 cores. I’m going to see if I can get this into the official branch.

**Comment by lukeweber** [comment]
Cool thanks.
