### ISSUE TITLE
Not receiving roster updates

### ISSUE THREAD

**Issue by wjwarren** [lukeweber/webrtc-jingle-client#25]
The VoiceClient doesn't seem to be receiving roster updates since rev 26dc98d402a5b463be54628f151ef0859552d1c9.

**Comment by lukeweber** [comment]
I think this has to do with the maven build system probably messing up the specialized builds. We fixed this today.

Probably need to run:
gclient sync
mvn install clean
./tools/badit.sh

**Comment by lukeweber** [comment]
Was using the wrong version.

**Comment by wjwarren** [comment]
I think you can close this one. Roster updates are now appearing just fine.
