### ISSUE TITLE
Undefined variable gtest_target_type

### ISSUE THREAD

**Issue by nikolajsheller** [lukeweber/webrtc-jingle-client#28]
Performing:

```
gclient config https://github.com/lukeweber/webrtc-jingle-client.git --name trunk
gclient sync
```

in a new folder results in the error:

```
Updating projects from gyp files...
<snip>
KeyError: 'Undefined variable gtest_target_type in trunk/webrtcjingle.gyp while trying to load trunk/webrtcjingle.gyp'
```

**Comment by lukeweber** [comment]
Want to run all the commands including the source command?

You need to run the first command to be able to get the source to run the source build/android/envsetup.sh command but that error shouldn't necessarily matter.

If that doesn't work ill do a clean checkout in a few hours after dinner and see if I can get rid of it.

**Comment by lukeweber** [comment]
I see the variable defined in trunk/build/common.gypi, and doing a clean checkout on my computer, I'm not seeing this error. Can you provide more detail, os, etc?

Thanks

**Comment by nikolajsheller** [comment]
Hello Luke

Thank you for your quick response!

I seem to have overlooked an entry to 'android-ndk-r8b' in my path, that
took precedence over my entry to 'android-ndk-r8'.
Removing the entry to 'android-ndk-r8b' results in a clean build.

My apologies for spamming the bug list.

Regards
-Nikolaj Sheller
