### ISSUE TITLE
Can't logout/login with current client

### ISSUE THREAD

**Issue by jreyes** [lukeweber/webrtc-jingle-client#3]
With the current client I do a login -> logout -> login but not able to login a second time. Please confirm.

**Comment by nickflink** [comment]
Yea that's a problem we still haven't fixed.  The work around is to release
and then to initialize the client again.  I'm on vacation so I won't be
able to fix it in the next two weeks, but will continue to look at it when
I get back.

On Tue, Jul 31, 2012 at 7:21 AM, Johann Reyes <
reply@reply.github.com

> wrote:
> 
> With the current client I do a login -> logout -> login but not able to
> login a second time. Please confirm.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/lukeweber/webrtc-jingle-client/issues/3

## 

Nick Flink
Calle de San Joaquín, 4,
28004 Madrid,
Spain
+34 911394660 (land line)
+34 627256841 (mobile)

**Comment by lukeweber** [comment]
Definitely broken.

Nick was tracking this. With a new pump every time i think its fixed, but we were trying to get to the root of it.

----- Reply message -----
From: "Johann Reyes" reply@reply.github.com
To: "Luke Weber" luke.weber@gmail.com
Subject: [webrtc-jingle-client] Can't logout/login with current client (#3)
Date: Tue, Jul 31, 2012 07:21

With the current client I do a login -> logout -> login but not able to login a second time. Please confirm.

---

Reply to this email directly or view it on GitHub:
https://github.com/lukeweber/webrtc-jingle-client/issues/3
