### ISSUE TITLE
Simultaneous calls handled incorrectly 

### ISSUE THREAD

**Issue by dmonakhov** [lukeweber/webrtc-jingle-client#41]
If new incomming call happen during other already in proggress current call activity will be replaced via
incommingCall. After that it becomes impossible to cancel current call.
Flow:
Alice                                       Bob                      Fred  
    |<------------Incoming call---|  
    | call_is_in_progress          |
    |<--------------------------------------Incoming call--|
    |  ------------BUSY------------------------------------>|
    |
  But at this moment Alice-Bob CallActivity hidden, and BuddyView is visiable, so it is impossible to destroy the call.

AFAIU bug was introduced during migration new Jreyes's API.

**Comment by lukeweber** [comment]
Yes it was. The old logic was overly simple, just sending a busy.

Libjingle in it's current state should be able to handle many outgoing/incoming calls at the same time, although this isn't throughly tested.

Basically in java, there should only be a pointer to the call_id with focus, but there should be an array of many call_ids. When you make a call, you might call two endpoints namely jid/res1 and jid/res2 and wait to see which one accepts, then tear down the other.

We're a ways from that, but that would be the progression.

**Comment by jreyes** [comment]
Please close this issue
