### ISSUE TITLE
Running without linking errors

### ISSUE THREAD

**Issue by mrquincle** [lukeweber/webrtc-jingle-client#5]
Dear developers,

Everything builds out of the box, but it doesn't seem to run:

```
BUILD SUCCESSFUL
Total time: 11 seconds
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
Failure
1276 KB/s (15939098 bytes in 12.194s)
pkg: /data/local/tmp/VoiceClient-debug.apk
Success
Starting: Intent { act=android.intent.action.VIEW cmp=com.tuenti.voice/.VoiceClientActivity }
Debug package com.tuenti.voice
mktemp: too few X's in template `gdb_apk'
/opt/webrtcjingleproject/trunk/build/android/gdb_apk: line 32: $TMPOUT: ambiguous redirect
```

If I open the project in Eclipse and copy the libvoiceclient.so file to libs/armeabi (52MB!) then I get a java.lang.UnsatisfiedLinkError: Couldn't load voiceclient: findLibrary returned null.

Format:

```
libs/armeabi/libvoiceclient.so: ELF 32-bit LSB shared object, ARM, version 1 (SYSV), dynamically linked, not stripped
```

I also stripped it using: arm-linux-androideabi-strip -g libs/armeabi/libvoiceclient.so which makes everything faster (15 MB), and leads actually to a display with a series of buttons. However, pressing one gives a java.lang.UnsatisfiedLinkError for nativeInit. So apparently I stripped to much!? Anyway, gdb doesn't like it apparently.

Anyway, before I delve into this I would like to know if I do something wrong. I'm on Ubuntu 12.04 and did just ./badit.sh -s. Is there maybe a release version that is a little smaller (I have a Nexus 1).

Thanks in advance!

**Comment by lukeweber** [comment]
So this our more experimental build option. To build release you would have to just run make in trunk. Badit builds type debug. 

As well noticed you were running an older ndk. I would try the latest. 

Last webrtc-client should work and be smaller and more reliab

----- Reply message -----
From: "Anne van Rossum" reply@reply.github.com
To: "Luke Weber" luke.weber@gmail.com
Subject: [webrtc-jingle-client] Running without linking errors (#5)
Date: Tue, Jul 31, 2012 22:22

Dear developers,

Everything builds out of the box, but it doesn't seem to run:

```
BUILD SUCCESSFUL
Total time: 11 seconds
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
Failure
1276 KB/s (15939098 bytes in 12.194s)
pkg: /data/local/tmp/VoiceClient-debug.apk
Success
Starting: Intent { act=android.intent.action.VIEW cmp=com.tuenti.voice/.VoiceClientActivity }
Debug package com.tuenti.voice
mktemp: too few X's in template `gdb_apk'
/opt/webrtcjingleproject/trunk/build/android/gdb_apk: line 32: $TMPOUT: ambiguous redirect
```

If I open the project in Eclipse and copy the libvoiceclient.so file to libs/armeabi (52MB!) then I get a java.lang.UnsatisfiedLinkError: Couldn't load voiceclient: findLibrary returned null.

Format:

```
libs/armeabi/libvoiceclient.so: ELF 32-bit LSB shared object, ARM, version 1 (SYSV), dynamically linked, not stripped
```

I also stripped it using: arm-linux-androideabi-strip -g libs/armeabi/libvoiceclient.so which makes everything faster (15 MB), and leads actually to a display with a series of buttons. However, pressing one gives a java.lang.UnsatisfiedLinkError for nativeInit. So apparently I stripped to much!? Anyway, gdb doesn't like it apparently.

Anyway, before I delve into this I would like to know if I do something wrong. I'm on Ubuntu 12.04 and did just ./badit.sh -s. Is there maybe a release version that is a little smaller (I have a Nexus 1).

Thanks in advance!

---

Reply to this email directly or view it on GitHub:
https://github.com/lukeweber/webrtc-jingle-client/issues/5

**Comment by lukeweber** [comment]
Excuse me meant webrtc-jingle with associated instructions should be the most reliable. I have had this system working, but sometimes has had wrinkles. If you're copying manually you'll also need the gdb that's in voiceclient/libs directory in out. In working on getting this system up but has issues. Chromium doesn't support armv5. This build process is similar to chromium but they haven't yet upstreamed a ton of code that would make this smoother.

Luke

----- Reply message -----

**Comment by mrquincle** [comment]
Okay, let's try "make all", that builds fine indeed and now in "Release", but adding -debug to the filename. I had also to change the jni_generator.py to comment the lines:

```
#    if len(natives) == 0 and len(called_by_natives) == 0:
#      raise SyntaxError('Unable to find any JNI methods for %s.' %
#                        fully_qualified_class)
```

That's not a good sign. 

So, you'd recommend to go back to webrtc-jingle, because it is more reliable? Then I will go back again. :-) Thanks for all the help!

**Comment by lukeweber** [comment]
Thanks for trying this out. Eventually the new one will be equal but we haven't figured out all of the funkyness yet of gyp. Anyways to not get errors just make the target webrtc_jingle

----- Reply message -----
From: "Anne van Rossum" reply@reply.github.com
To: "Luke Weber" luke.weber@gmail.com
Subject: [webrtc-jingle-client] Running without linking errors (#5)
Date: Tue, Jul 31, 2012 23:21

Okay, let's try "make all", that builds fine indeed and now in "Release", but adding -debug to the filename. I had also to change the jni_generator.py to comment the lines:

```
#    if len(natives) == 0 and len(called_by_natives) == 0:
#      raise SyntaxError('Unable to find any JNI methods for %s.' %
#                        fully_qualified_class)
```

That's not a good sign. 

So, you'd recommend to go back to webrtc-jingle, because it is more reliable? Then I will go back again. :-) Thanks for all the help!

---

**Comment by jreyes** [comment]
the libvoiceclient.so that you get building just move it to libs/armeabi directory that's how I'm running the example currently.

**Comment by lukeweber** [comment]
This issue should now be resolved. Sorry for the trouble.

https://github.com/lukeweber/chromium-trunk-build-override/commit/7f3c5248fa4f196328472d61f44d01216cb1b9e4

If you run gclient sync and then follow the steps a build should work. badit inside the source directory is with old instructions is probably still the safest, as I haven't gotten strip built into the gyp process yet for a release build. If you want to give a hand at it, more than welcome to try.
