### ISSUE TITLE
undefined reference error while building

### ISSUE THREAD

**Issue by tsudot** [lukeweber/webrtc-jingle-client#56]
The following error crops ups while building

SharedLibrary  : libjingle_unittest.so
SharedLibrary  : libvoiceclient.so
SharedLibrary  : libjingle_media_unittest.so
SharedLibrary  : libjingle_p2p_unittest.so
/home/tsudot/workspace/android-ndk-r8c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: /home/tsudot/workspace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/armeabi-v7a/objs-debug/voiceclient/**/**/**/client/voiceclient.o: in function tuenti::VoiceClient::InitializeS():jni/../../../client/voiceclient.cc:140: error: undefined reference to 'tuenti::VoiceClient::OnSignalStatsUpdate(char const_)'
collect2: ld returned 1 exit status
make: *_\* [/home/tsudot/workspace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/armeabi-v7a/libvoiceclient.so] Error 1
make: **\* Waiting for unfinished jobs....
/home/tsudot/workspace/android-ndk-r8c/toolchains/x86-4.6/prebuilt/linux-x86/bin/../lib/gcc/i686-linux-android/4.6/../../../../i686-linux-android/bin/ld: /home/tsudot/workspace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/x86/objs-debug/voiceclient/**/**/**/client/voiceclient.o: in function tuenti::VoiceClient::InitializeS():jni/../../../client/voiceclient.cc:133: error: undefined reference to 'tuenti::VoiceClient::OnSignalStatsUpdate(char const_)'
collect2: ld returned 1 exit status
make: *_\* [/home/tsudot/workspace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/x86/libvoiceclient.so] Error 1
make: Leaving directory `/home/tsudot/workspace/webrtcjingleproject/trunk/android/voice-client-core'

OS - Ubuntu 12.04

Am I missing something?

**Comment by nickflink** [comment]
You could merge in the pinned branch into master and that should fix it.
 It is a direct merge.  You should take care to discard any changes that
have been made to the DEPS file, as master should always have the up to
date code where pinned is locked down to specific revisions in every repo.
 I'll make sure to apply this merge first thing Tuesday when I get back,
unless someone gets to it before me.

On Sat, Jan 5, 2013 at 2:30 AM, Kunal Kerkar notifications@github.comwrote:

> The following error crops ups while building
> 
> SharedLibrary : libjingle_unittest.so
> SharedLibrary : libvoiceclient.so
> SharedLibrary : libjingle_media_unittest.so
> SharedLibrary : libjingle_p2p_unittest.so
> /home/tsudot/workspace/android-ndk-r8c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld:
> /home/tsudot/workspace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/armeabi-v7a/objs-debug/voiceclient/**/**/**/client/voiceclient.o:
> in function
> tuenti::VoiceClient::InitializeS():jni/../../../client/voiceclient.cc:140:
> error: undefined reference to
> 'tuenti::VoiceClient::OnSignalStatsUpdate(char const_)'
> collect2: ld returned 1 exit status
> make: *_*
> [/home/tsudot/workspace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/armeabi-v7a/libvoiceclient.so]
> Error 1
> make: **\* Waiting for unfinished jobs....
> /home/tsudot/workspace/android-ndk-r8c/toolchains/x86-4.6/prebuilt/linux-x86/bin/../lib/gcc/i686-linux-android/4.6/../../../../i686-linux-android/bin/ld:
> /home/tsudot/workspace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/x86/objs-debug/voiceclient/**/**/**/client/voiceclient.o:
> in function
> tuenti::VoiceClient::InitializeS():jni/../../../client/voiceclient.cc:133:
> error: undefined reference to
> 'tuenti::VoiceClient::OnSignalStatsUpdate(char const_)'
> collect2: ld returned 1 exit status
> make: *_*
> [/home/tsudot/workspace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/x86/libvoiceclient.so]
> Error 1
> make: Leaving directory
> `/home/tsudot/workspace/webrtcjingleproject/trunk/android/voice-client-core'
> 
> OS - Ubuntu 12.04
> 
> Am I missing something?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lukeweber/webrtc-jingle-client/issues/56.

## 

Nick Flink
Calle de San Joaquín, 4,
28004 Madrid,
Spain
+34 911394660 (land line)
+34 627256841 (mobile)

**Comment by nickflink** [comment]
FYI I've just pushed the fix for this, so if you update with master now it
should be working.

Sorry for the inconvenience.

On Sat, Jan 5, 2013 at 1:09 PM, Nick Flink nickflink@gmail.com wrote:

> You could merge in the pinned branch into master and that should fix it.
>  It is a direct merge.  You should take care to discard any changes that
> have been made to the DEPS file, as master should always have the up to
> date code where pinned is locked down to specific revisions in every repo.
>  I'll make sure to apply this merge first thing Tuesday when I get back,
> unless someone gets to it before me.
> 
> On Sat, Jan 5, 2013 at 2:30 AM, Kunal Kerkar notifications@github.comwrote:
> 
> > The following error crops ups while building
> > 
> > SharedLibrary : libjingle_unittest.so
> > SharedLibrary : libvoiceclient.so
> > SharedLibrary : libjingle_media_unittest.so
> > SharedLibrary : libjingle_p2p_unittest.so
> > /home/tsudot/workspace/android-ndk-r8c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld:
> > /home/tsudot/workspace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/armeabi-v7a/objs-debug/voiceclient/**/**/**/client/voiceclient.o:
> > in function
> > tuenti::VoiceClient::InitializeS():jni/../../../client/voiceclient.cc:140:
> > error: undefined reference to
> > 'tuenti::VoiceClient::OnSignalStatsUpdate(char const_)'
> > collect2: ld returned 1 exit status
> > make: *_*
> > [/home/tsudot/workspace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/armeabi-v7a/libvoiceclient.so]
> > Error 1
> > make: **\* Waiting for unfinished jobs....
> > /home/tsudot/workspace/android-ndk-r8c/toolchains/x86-4.6/prebuilt/linux-x86/bin/../lib/gcc/i686-linux-android/4.6/../../../../i686-linux-android/bin/ld:
> > /home/tsudot/workspace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/x86/objs-debug/voiceclient/**/**/**/client/voiceclient.o:
> > in function
> > tuenti::VoiceClient::InitializeS():jni/../../../client/voiceclient.cc:133:
> > error: undefined reference to
> > 'tuenti::VoiceClient::OnSignalStatsUpdate(char const_)'
> > collect2: ld returned 1 exit status
> > make: *_*
> > [/home/tsudot/workspace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/x86/libvoiceclient.so]
> > Error 1
> > make: Leaving directory
> > `/home/tsudot/workspace/webrtcjingleproject/trunk/android/voice-client-core'
> > 
> > OS - Ubuntu 12.04
> > 
> > Am I missing something?
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/lukeweber/webrtc-jingle-client/issues/56.
> 
> ## 
> 
> Nick Flink
> Calle de San Joaquín, 4,
> 28004 Madrid,
> Spain
> +34 911394660 (land line)
> +34 627256841 (mobile)

## 

Nick Flink
Calle de San Joaquín, 4,
28004 Madrid,
Spain
+34 911394660 (land line)
+34 627256841 (mobile)
