### ISSUE TITLE
not able to run the application

### ISSUE THREAD

**Issue by walidsynclio** [lukeweber/webrtc-jingle-client#58]
Hi,
I am able to run ./build.sh without any error.
after this I tried to run mvn install but it stops with error.
How do I import the project in eclipse and build apk.

[INFO] Scanning for projects...
[INFO] Reactor build order: 
[INFO]   Tuenti Voice Client Parent
[INFO]   Tuenti Voice Client Core
[INFO]   Tuenti Voice Client AIDL
[INFO]   Tuenti Voice Client Example
[INFO] snapshot com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.3.3-SNAPSHOT: checking for updates from oss.sonatype.org-jayway-snapshots
[WARNING] **\* CHECKSUM FAILED - Checksum failed on download: local = '4f81f028b7a6cc7a3ca6fcefcecd9b4394948293'; remote = 'fec5ee1e6da804cae984058e8aec7b621918cc40' - RETRYING
[WARNING] **\* CHECKSUM FAILED - Checksum failed on download: local = '4f81f028b7a6cc7a3ca6fcefcecd9b4394948293'; remote = 'fec5ee1e6da804cae984058e8aec7b621918cc40' - IGNORING
[INFO] ------------------------------------------------------------------------
[INFO] Building Tuenti Voice Client Parent
[INFO]    task-segment: [install]
[INFO] ------------------------------------------------------------------------
[INFO] [site:attach-descriptor {execution: default-attach-descriptor}]
[INFO] [install:install {execution: default-install}]
[INFO] Installing /media/newderive/libjingleNew/trunk/android/pom.xml to /home/abul/.m2/repository/com/tuenti/voice/voice-parent/1.0-SNAPSHOT/voice-parent-1.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] Building Tuenti Voice Client Core
[INFO]    task-segment: [install]
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Internal error in the plugin manager executing goal 'com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.3.3-SNAPSHOT:generate-sources': Unable to find the mojo 'generate-sources' (or one of its required components) in the plugin 'com.jayway.maven.plugins.android.generation2:android-maven-plugin'
Component descriptor cannot be found in the component repository: org.sonatype.aether.RepositorySystem.
[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13 seconds
[INFO] Finished at: Wed Jan 09 15:10:56 IST 2013
[INFO] Final Memory: 28M/68M
[INFO] ------------------------------------------------------------------------

**Comment by lukeweber** [comment]
Googling the error turned this up:
https://github.com/rtyley/agit/issues/48

Verified I get the same error with maven 2.2.1.

I've committed https://github.com/lukeweber/webrtc-jingle-client/commit/798681325d10bd5b81ef00e3f460f54e0b434f7e to enforce at the maven level that you install maven 3.0.3 or higher else you'll receive an error.

Upgrade your maven and you'll be able to build.

As far as integration, unless you want to build something else, this is what the maven plugin that we're using suggests to do, but haven't used it:
http://code.google.com/p/maven-android-plugin/wiki/EclipseIntegration

If that doesn't work, please create a separate ticket and we'll see if anyone has further thoughts.

**Comment by walidsynclio** [comment]
Hi,
Thank you for the solution.
But after updating my maven to 3.0.4
I am getting this error when I run "mvn install"

[INFO] ------------------------------------------------------------------------
[INFO] Building Tuenti Voice Client Core 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven-version) @ voice-core ---
[INFO] 
[INFO] --- android-maven-plugin:3.3.3-SNAPSHOT:generate-sources (default-generate-sources) @ voice-core ---
[INFO] ANDROID-904-002: Found aidl files: Count = 0
[INFO] ANDROID-904-002: Found aidl files: Count = 0
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Tuenti Voice Client Parent ........................ SUCCESS [0.327s]
[INFO] Tuenti Voice Client Core .......................... FAILURE [2.060s]
[INFO] Tuenti Voice Client AIDL .......................... SKIPPED
[INFO] Tuenti Voice Client Example ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.021s
[INFO] Finished at: Wed Jan 09 20:02:21 IST 2013
[INFO] Final Memory: 9M/21M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.3.3-SNAPSHOT:generate-sources (default-generate-sources) on project voice-core: Execution default-generate-sources of goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.3.3-SNAPSHOT:generate-sources failed: Invalid SDK: Platform/API level 14 not available. This command should give you all you need:
[ERROR] /media/newderive/adt-bundle-linux/sdk/tools/android update sdk --no-ui --obsolete --force
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :voice-core

**Comment by jreyes** [comment]
Did you run the command that the error is giving?

/media/newderive/adt-bundle-linux/sdk/tools/android update sdk --no-ui --obsolete --force

**Comment by lukeweber** [comment]
Thanks Johann, that should work. As well I've added a bit of magic to the build script to do some detections on some of the core build stuff and even download the sdk update if you want.

Specifically the command that I tested was $ANDROID_SDK_ROOT/tools/android update sdk -u --filter android-14

https://github.com/lukeweber/webrtc-jingle-client/commit/6aafd81d0cac752817f89a1a4b8e277b7c5c449d
