### ISSUE TITLE
Ejabberd STUN Server Binding Error

### ISSUE THREAD

**Issue by chathudan** [lukeweber/webrtc-jingle-client#66]
Why Does this error Come 
D(<0.364.0>:ejabberd_stun:78) : got:
{stun,request,1,51595046,59834731914394464689121067847, [3], undefined,undefined,undefined,undefined,undefined,undefined,undefined, undefined,undefined,[]}
=INFO REPORT==== 2013-02-08 18:39:21 ===
D(<0.364.0>:ejabberd_stun:81) : sent:
{stun,error,1,51595046,59834731914394464689121067847,[],<<"ejabberd 2.1.x">>,
undefined,undefined,undefined,undefined,undefined,undefined,undefined,
{420,<<"Unknown Attribute">>},
[3]}

**Comment by lukeweber** [comment]
Might be the old stun rfc on ejabberd. Check that it fully implements the
new stun rfc. Might see rfc5766 for references to what I'm talking about.

**Comment by lukeweber** [comment]
This is an issue with the stun on ejabberd. Google to see which version they support.
