### ISSUE TITLE
Maven compilation issue.

### ISSUE THREAD

**Issue by veereshkalmath** [lukeweber/webrtc-jingle-client#68]
Hi,
  I'm building by following the Readme.md instructions. I'm getting the following build error. I'm new to maven please help me out.

Is there a way to import these projects in eclipse? I installed m2e and imported maven projects, showing lot of errors.

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Tuenti Voice Client Parent
[INFO] Tuenti Voice Client Core
[INFO] Tuenti Voice Client AIDL
[INFO] Tuenti Voice Client Example
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Tuenti Voice Client Parent 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ voice-parent ---
[INFO] Installing /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/pom.xml to /Users/veereshkalmath/.m2/repository/com/tuenti/voice/voice-parent/1.0-SNAPSHOT/voice-parent-1.0-SNAPSHOT.pom
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Tuenti Voice Client Core 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven-version) @ voice-core ---
[INFO] 
[INFO] --- android-maven-plugin:3.5.1-SNAPSHOT:generate-sources (default-generate-sources) @ voice-core ---
[INFO] ANDROID-904-002: Found aidl files: Count = 0
[INFO] ANDROID-904-002: Found aidl files: Count = 0
[INFO] Manifest merging disabled. Using project manifest only
[INFO] /AndroidSDK/android-sdk-macosx/platform-tools/aapt [package, -m, -J, /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/target/generated-sources/r, -M, /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/AndroidManifest.xml, -S, /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/res, --auto-add-overlay, -I, /AndroidSDK/android-sdk-macosx/platforms/android-14/android.jar]
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ voice-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/src/main/resources
[INFO] skip non existing resourceDirectory /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/target/generated-sources/extracted-dependencies/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ voice-core ---
[INFO] Compiling 2 source files to /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/target/classes
[INFO] 
[INFO] --- android-maven-plugin:3.5.1-SNAPSHOT:proguard (default-proguard) @ voice-core ---
[INFO] 
[INFO] --- native-maven-plugin:1.0-alpha-7:javah (generateNative) @ voice-core ---
[INFO] /bin/sh -c cd /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core && javah -d /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/jni -classpath /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/target/classes:/Users/veereshkalmath/.m2/repository/com/google/android/android/4.0.1.2/android-4.0.1.2.jar:/Users/veereshkalmath/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar:/Users/veereshkalmath/.m2/repository/org/apache/httpcomponents/httpclient/4.0.1/httpclient-4.0.1.jar:/Users/veereshkalmath/.m2/repository/org/apache/httpcomponents/httpcore/4.0.1/httpcore-4.0.1.jar:/Users/veereshkalmath/.m2/repository/commons-codec/commons-codec/1.3/commons-codec-1.3.jar:/Users/veereshkalmath/.m2/repository/org/khronos/opengl-api/gl1.1-android-2.1_r1/opengl-api-gl1.1-android-2.1_r1.jar:/Users/veereshkalmath/.m2/repository/xerces/xmlParserAPIs/2.6.2/xmlParserAPIs-2.6.2.jar:/Users/veereshkalmath/.m2/repository/xpp3/xpp3/1.1.4c/xpp3-1.1.4c.jar:/Users/veereshkalmath/.m2/repository/org/json/json/20080701/json-20080701.jar -verbose com.tuenti.voice.core.VoiceClient
[ Search Path: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/jsfd.jar:/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/classes.jar:/System/Library/Frameworks/JavaVM.framework/Frameworks/JavaRuntimeSupport.framework/Resources/Java/JavaRuntimeSupport.jar:/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/ui.jar:/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/laf.jar:/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/sunrsasign.jar:/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/jsse.jar:/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/jce.jar:/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/charsets.jar//Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/target/classes:/Users/veereshkalmath/.m2/repository/com/google/android/android/4.0.1.2/android-4.0.1.2.jar:/Users/veereshkalmath/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar:/Users/veereshkalmath/.m2/repository/org/apache/httpcomponents/httpclient/4.0.1/httpclient-4.0.1.jar:/Users/veereshkalmath/.m2/repository/org/apache/httpcomponents/httpcore/4.0.1/httpcore-4.0.1.jar:/Users/veereshkalmath/.m2/repository/commons-codec/commons-codec/1.3/commons-codec-1.3.jar:/Users/veereshkalmath/.m2/repository/org/khronos/opengl-api/gl1.1-android-2.1_r1/opengl-api-gl1.1-android-2.1_r1.jar:/Users/veereshkalmath/.m2/repository/xerces/xmlParserAPIs/2.6.2/xmlParserAPIs-2.6.2.jar:/Users/veereshkalmath/.m2/repository/xpp3/xpp3/1.1.4c/xpp3-1.1.4c.jar:/Users/veereshkalmath/.m2/repository/org/json/json/20080701/json-20080701.jar ]
[No need to update file /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/jni/com_tuenti_voice_core_VoiceClient.h]
[search path for source files: /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/target/classes,/Users/veereshkalmath/.m2/repository/com/google/android/android/4.0.1.2/android-4.0.1.2.jar,/Users/veereshkalmath/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar,/Users/veereshkalmath/.m2/repository/org/apache/httpcomponents/httpclient/4.0.1/httpclient-4.0.1.jar,/Users/veereshkalmath/.m2/repository/org/apache/httpcomponents/httpcore/4.0.1/httpcore-4.0.1.jar,/Users/veereshkalmath/.m2/repository/commons-codec/commons-codec/1.3/commons-codec-1.3.jar,/Users/veereshkalmath/.m2/repository/org/khronos/opengl-api/gl1.1-android-2.1_r1/opengl-api-gl1.1-android-2.1_r1.jar,/Users/veereshkalmath/.m2/repository/xerces/xmlParserAPIs/2.6.2/xmlParserAPIs-2.6.2.jar,/Users/veereshkalmath/.m2/repository/xpp3/xpp3/1.1.4c/xpp3-1.1.4c.jar,/Users/veereshkalmath/.m2/repository/org/json/json/20080701/json-20080701.jar]
[search path for class files: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/jsfd.jar,/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/classes.jar,/System/Library/Frameworks/JavaVM.framework/Frameworks/JavaRuntimeSupport.framework/Resources/Java/JavaRuntimeSupport.jar,/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/ui.jar,/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/laf.jar,/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/sunrsasign.jar,/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/jsse.jar,/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/jce.jar,/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/charsets.jar,/System/Library/Java/Extensions/AppleScriptEngine.jar,/System/Library/Java/Extensions/dns_sd.jar,/System/Library/Java/Extensions/j3daudio.jar,/System/Library/Java/Extensions/j3dcore.jar,/System/Library/Java/Extensions/j3dutils.jar,/System/Library/Java/Extensions/jai_codec.jar,/System/Library/Java/Extensions/jai_core.jar,/System/Library/Java/Extensions/mlibwrapper_jai.jar,/System/Library/Java/Extensions/MRJToolkit.jar,/System/Library/Java/Extensions/QTJava.zip,/System/Library/Java/Extensions/vecmath.jar,/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/lib/ext/apple_provider.jar,/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/lib/ext/dnsns.jar,/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/lib/ext/localedata.jar,/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/lib/ext/sunjce_provider.jar,/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/lib/ext/sunpkcs11.jar,/Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/target/classes,/Users/veereshkalmath/.m2/repository/com/google/android/android/4.0.1.2/android-4.0.1.2.jar,/Users/veereshkalmath/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar,/Users/veereshkalmath/.m2/repository/org/apache/httpcomponents/httpclient/4.0.1/httpclient-4.0.1.jar,/Users/veereshkalmath/.m2/repository/org/apache/httpcomponents/httpcore/4.0.1/httpcore-4.0.1.jar,/Users/veereshkalmath/.m2/repository/commons-codec/commons-codec/1.3/commons-codec-1.3.jar,/Users/veereshkalmath/.m2/repository/org/khronos/opengl-api/gl1.1-android-2.1_r1/opengl-api-gl1.1-android-2.1_r1.jar,/Users/veereshkalmath/.m2/repository/xerces/xmlParserAPIs/2.6.2/xmlParserAPIs-2.6.2.jar,/Users/veereshkalmath/.m2/repository/xpp3/xpp3/1.1.4c/xpp3-1.1.4c.jar,/Users/veereshkalmath/.m2/repository/org/json/json/20080701/json-20080701.jar]
[loading /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/target/classes/com/tuenti/voice/core/VoiceClient.class]
[loading java/lang/Object.class(java/lang:Object.class)]
[loading java/lang/Throwable.class(java/lang:Throwable.class)]
[loading java/lang/Class.class(java/lang:Class.class)]
[loading java/lang/String.class(java/lang:String.class)]
[loading android/content/Context.class(android/content:Context.class)]
[done in 736 ms]
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ voice-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ voice-core ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.13:test (default-test) @ voice-core ---
[INFO] 
[INFO] --- android-maven-plugin:3.5.1-SNAPSHOT:ndk-build (executeNdk) @ voice-core ---
[INFO] executing 4 parallel jobs
[INFO] /AndroidNDK/android-ndk-r8d/ndk-build [-C, /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core, NDK_APPLICATION_MK=jni/default_debug.mk, -j, 4, NDK_APP_OUT=/Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug, all]
[INFO] /AndroidNDK/android-ndk-r8d/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/armeabi-v7a/objs-debug/jingle_media_unittest/talk/media/base/filemediaengine_unittest.o: in function std::basic_ostream<char, std::char_traits<char> >::sentry::~sentry():/AndroidNDK/android-ndk-r8d/sources/cxx-stl/stlport/stlport/stl/_ostream.h:187: error: undefined reference to 'std::uncaught_exception()'
[INFO] collect2: ld returned 1 exit status
[INFO] make: **\* [/Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/armeabi-v7a/libjingle_media_unittest.so] Error 1
[INFO] make: **\* Waiting for unfinished jobs....
[INFO] /AndroidNDK/android-ndk-r8d/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/armeabi-v7a/objs-debug/jingle_unittest/talk/base/asynchttprequest_unittest.o: in function std::basic_ostream<char, std::char_traits<char> >::sentry::~sentry():/AndroidNDK/android-ndk-r8d/sources/cxx-stl/stlport/stlport/stl/_ostream.h:187: error: undefined reference to 'std::uncaught_exception()'
[INFO] collect2: ld returned 1 exit status
[INFO] make: **\* [/Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/armeabi-v7a/libjingle_unittest.so] Error 1
[INFO] /AndroidNDK/android-ndk-r8d/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/armeabi-v7a/objs-debug/voiceclient/voiceclient_main.o: in function std::basic_ostream<char, std::char_traits<char> >::sentry::~sentry():/AndroidNDK/android-ndk-r8d/sources/cxx-stl/stlport/stlport/stl/_ostream.h:187: error: undefined reference to 'std::uncaught_exception()'
[INFO] collect2: ld returned 1 exit status
[INFO] make: **\* [/Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/armeabi-v7a/libvoiceclient.so] Error 1
[INFO] /AndroidNDK/android-ndk-r8d/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/armeabi-v7a/objs-debug/jingle_p2p_unittest/talk/media/base/testutils.o: in function std::basic_ostream<char, std::char_traits<char> >::sentry::~sentry():/AndroidNDK/android-ndk-r8d/sources/cxx-stl/stlport/stlport/stl/_ostream.h:187: error: undefined reference to 'std::uncaught_exception()'
[INFO] collect2: ld returned 1 exit status
[INFO] make: **\* [/Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/armeabi-v7a/libjingle_p2p_unittest.so] Error 1
[ERROR] Error while executing: ANDROID-040-001: Could not execute: Command = /bin/sh -c cd /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core && /AndroidNDK/android-ndk-r8d/ndk-build -C /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core NDK_APPLICATION_MK=jni/default_debug.mk -j 4 NDK_APP_OUT=/Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug all, Result = 2
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Tuenti Voice Client Parent ........................ SUCCESS [0.648s]
[INFO] Tuenti Voice Client Core .......................... FAILURE [51.427s]
[INFO] Tuenti Voice Client AIDL .......................... SKIPPED
[INFO] Tuenti Voice Client Example ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 53.424s
[INFO] Finished at: Tue Feb 19 14:55:44 GMT+05:30 2013
[INFO] Final Memory: 15M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.5.1-SNAPSHOT:ndk-build (executeNdk) on project voice-core: ANDROID-040-001: Could not execute: Command = /bin/sh -c cd /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core && /AndroidNDK/android-ndk-r8d/ndk-build -C /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core NDK_APPLICATION_MK=jni/default_debug.mk -j 4 NDK_APP_OUT=/Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug all, Result = 2 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
## [ERROR]   mvn <goals> -rf :voice-core

/AndroidNDK/android-ndk-r8d/ndk-build -C /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core NDK_APPLICATION_MK=jni/default_debug.mk -j4 NDK_APP_OUT=/Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug all

When I execute manually the above command the build fails with error

Build unittest for libjingle
make: Entering directory `/Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core'
SharedLibrary  : libjingle_media_unittest.so
SharedLibrary  : libjingle_p2p_unittest.so
SharedLibrary  : libjingle_unittest.so
SharedLibrary  : libvoiceclient.so
/AndroidNDK/android-ndk-r8d/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/armeabi-v7a/objs-debug/jingle_media_unittest/talk/media/base/filemediaengine_unittest.o: in function std::basic_ostream<char, std::char_traits<char> >::sentry::~sentry():/AndroidNDK/android-ndk-r8d/sources/cxx-stl/stlport/stlport/stl/_ostream.h:187: error: undefined reference to 'std::uncaught_exception()'
collect2: ld returned 1 exit status
make: *** [/Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/armeabi-v7a/libjingle_media_unittest.so] Error 1
make: *** Waiting for unfinished jobs....
/AndroidNDK/android-ndk-r8d/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/armeabi-v7a/objs-debug/voiceclient/voiceclient_main.o: in function std::basic_ostream<char, std::char_traits<char> >::sentry::~sentry():/AndroidNDK/android-ndk-r8d/sources/cxx-stl/stlport/stlport/stl/_ostream.h:187: error: undefined reference to 'std::uncaught_exception()'
collect2: ld returned 1 exit status
make: *** [/Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/armeabi-v7a/libvoiceclient.so] Error 1
/AndroidNDK/android-ndk-r8d/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/armeabi-v7a/objs-debug/jingle_p2p_unittest/talk/media/base/testutils.o: in function std::basic_ostream<char, std::char_traits<char> >::sentry::~sentry():/AndroidNDK/android-ndk-r8d/sources/cxx-stl/stlport/stlport/stl/_ostream.h:187: error: undefined reference to 'std::uncaught_exception()'
collect2: ld returned 1 exit status
make: *** [/Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/armeabi-v7a/libjingle_p2p_unittest.so] Error 1
/AndroidNDK/android-ndk-r8d/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: /Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/armeabi-v7a/objs-debug/jingle_unittest/talk/base/asynchttprequest_unittest.o: in function std::basic_ostream<char, std::char_traits<char> >::sentry::~sentry():/AndroidNDK/android-ndk-r8d/sources/cxx-stl/stlport/stlport/stl/_ostream.h:187: error: undefined reference to 'std::uncaught_exception()'
collect2: ld returned 1 exit status
make: *** [/Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/armeabi-v7a/libjingle_unittest.so] Error 1
make: Leaving directory`/Users/veereshkalmath/AndroidWorkSpace/webrtcjingleproject/trunk/android/voice-client-core'

**Comment by lukeweber** [comment]
Has to do I think with stlport.a being copied from the ndk to your build
cache directory. In this case I think the old stlport from a previous ndk
is mixing with the headers in the new.Kill all your build cache in
voice-client-core/obj with a good ole rm -rf. Then rebuild and should work.
If you're feeling lazy you could try to just remove stlport from your
cache, but might be other issues from the old ndk.

**Comment by veereshkalmath** [comment]
Yes this solved the issue. Thanks for the info.

**Comment by TangTieuLinh** [comment]
Dear all,
I want to make voice chat application with webrtc-jingle-client. I can use both Gmail account on two android devices to call success. But when I log in with  account  is not a Gmail account,  i can log in,  receive presence but  I can not call. And if i call i will receive information "ClientSignalingThread::OnSessionError ERROR_ACK_TIME - no ack response to signaling, client not available" from LogCat.
Can you help me ?

**Comment by chathudan** [comment]
use your own turn server and try

**Comment by TangTieuLinh** [comment]
I don't have Turn Server.
But when i build for IOS device, I used account my company that is not Gmail account and i could call successful. Only Android device, i can't call.

**Comment by chathudan** [comment]
Are the android and iOS device are in same network ? put all devices in
same network and try

**Comment by TangTieuLinh** [comment]
Yes. All devices in same network because i use same wifi to connection.

**Comment by TangTieuLinh** [comment]
I changed some file in voice-defines.h and then I rebuilt project and i called successful with my company account. But I don't combine jingle lib with smack lib because my app use smack library for chat.
Can you help me ?
Thank you in advance.
