### ISSUE TITLE
Not able to build from latest branch

### ISSUE THREAD

**Issue by walidsynclio** [lukeweber/webrtc-jingle-client#75]
I have followed your instruction to build it on android.
there is no such file
android/voice-client-example/src/main/java/com/tuenti/voice/example/ui/LoginView.java.

when I do cd trunk/android/voice-client-core && ./build.sh

Assembler messages:
Fatal error: invalid -march= option: `armv5te'
Assembler messages:
make: *** [/home/abul/works/webrtclibjingle/trunk/android/voice-client-core/obj/default_debug/local/armeabi/objs-debug/jingle/talk/base/dbus.o] Error 1
make: *** Waiting for unfinished jobs....
Fatal error: invalid -march= option:`armv5te'
make: **\* [/home/abul/works/webrtclibjingle/trunk/android/voice-client-core/obj/default_debug/local/armeabi/objs-debug/jingle/talk/base/libdbusglibsymboltable.o] Error 1
Assembler messages:
Fatal error: invalid -march= option: `armv5te'
make: *** [/home/abul/works/webrtclibjingle/trunk/android/voice-client-core/obj/default_debug/local/armeabi/objs-debug/jingle/talk/base/linux.o] Error 1
make: Leaving directory`/home/abul/works/webrtclibjingle/trunk/android/voice-client-core'

Is there anything I am missing.
I have been trying to get this thing to work from almost 2 months and move to some other work in between.
Please help, want to try this.
demo app in webrtc trunk for android does not work smooth and video freezes or becomes slow. 
20% of the time video does not show even if I can see data is flowing both side.
I really want to try this one.

Thanks you...

**Comment by lukeweber** [comment]
First video won't work on this one. I've tried the demo app, and it's
nothing to write home about. I just use slightly different signaling as a
preference and I maintain code that actually works on android for network,
and a few small bugfixes.

If you want to give this a shot, you need to follow the instructions in the
README, including maven build.

If you're on windows, then install a linux vm, with sufficient space, at
least 10gb and then follow the instructions in the readme. the build.sh
command only builds the core ndk native files, in a manual way, and assumes
all is setup correctly. It's helpful for debugging the c++ build only in
special circumstances.

**Comment by walidsynclio** [comment]
Thanks for your reply,
I would like to try this even without video.

I am using Ubuntu 64 bit.
have maven and all other dependencies setup as per README
sync a fresh copy in a new directory, still all same.
I there anything specific I have to take care.

Thanks

**Comment by nickflink** [comment]
Could you show us the output fo the ./tools/badit_android.py tool?

On Wed, Mar 27, 2013 at 2:00 PM, walidsynclio notifications@github.comwrote:

> Thanks for your reply,
> I would like to try this even without video.
> 
> I am using Ubuntu 64 bit.
> have maven and all other dependencies setup as per README
> sync a fresh copy in a new directory, still all same.
> I there anything specific I have to take care.
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lukeweber/webrtc-jingle-client/issues/75#issuecomment-15521680
> .

## 

Nick Flink
Calle de San Joaquín, 4,
28004 Madrid,
Spain
+34 911394660 (land line)
+34 627256841 (mobile)

**Comment by walidsynclio** [comment]
Also when I do,     gclient sync
I get this Error
1>    are supported and installed on your system.
1>perl: warning: Falling back to the standard locale ("C").
1>No submodule mapping found in .gitmodules for path 'base'
Error: Command git clone --progress -b master https://github.com/lukeweber/webrtc-jingle-client.git /home/abul/works/webrtcjingleproject/trunk --recursive returned non-zero exit status 1 in /home/abul/works/webrtcjingleproject

if again type gclient sync it proceeds

I am sorry but where do I find
 ./tools/badit_android.py

Thank you

**Comment by walidsynclio** [comment]
Output of badit_android.py

INFO:**main**:Running with:
INFO:**main**:  profile: default_debug
INFO:**main**:  log-level: INFO
INFO:**main**:  task-mask: 29
INFO:**main**:  serial: None
ERROR:**main**:You're missing android-14, which is required
ERROR:**main**:You can install it by copy pasting the below command
/home/abul/Downloads/sdk/tools/android update sdk -u --filter android-14

I have latest android sdk. I think its api level 17

**Comment by nickflink** [comment]
it's ~/webrtcjingleproject/trunk/tools/badit on my machine.

https://github.com/lukeweber/webrtc-jingle-client/blob/master/tools/badit_android.pyin
the repository.

On Wed, Mar 27, 2013 at 2:09 PM, walidsynclio notifications@github.comwrote:

> Output of badit_android.py
> 
> INFO:**main**:Running with:
> INFO:**main**: profile: default_debug
> INFO:**main**: log-level: INFO
> INFO:**main**: task-mask: 29
> INFO:**main**: serial: None
> ERROR:**main**:You're missing android-14, which is required
> ERROR:**main**:You can install it by copy pasting the below command
> /home/abul/Downloads/sdk/tools/android update sdk -u --filter android-14
> 
> I have latest android sdk. I think its api level 17
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lukeweber/webrtc-jingle-client/issues/75#issuecomment-15522105
> .

## 

Nick Flink
Calle de San Joaquín, 4,
28004 Madrid,
Spain
+34 911394660 (land line)
+34 627256841 (mobile)

**Comment by walidsynclio** [comment]
Gotcha ! thanks
when I run ./tools/badit_android.py
I get
INFO:**main**:Running with:
INFO:**main**: profile: default_debug
INFO:**main**: log-level: INFO
INFO:**main**: task-mask: 29
INFO:**main**: serial: None
ERROR:**main**:You're missing android-14, which is required
ERROR:**main**:You can install it by copy pasting the below command
/home/abul/Downloads/sdk/tools/android update sdk -u --filter android-14

I have latest android sdk. I think its api level 17

**Comment by lukeweber** [comment]
android-14 != 17

Closing this issue. Please follow the instructions, including the output of any script. For example, did you try running the command that the script asked you to run?

**Comment by walidsynclio** [comment]
Now its NDK

INFO:**main**:Running with:
INFO:**main**:  profile: default_debug
INFO:**main**:  log-level: INFO
INFO:**main**:  task-mask: 29
INFO:**main**:  serial: None
ERROR:**main**:Please install a supported NDK version:
    r8 r8d

Looks like we can not download a older verison of ndk.
Current is r8e but this supports r8 or r8d.

**Comment by walidsynclio** [comment]
Hi,
I saw you have make changes to support ndk-r8e
But still I am not able to build it.

Error I got:

Assembler messages:
Fatal error: invalid -march= option: `armv5te'
Assembler messages:
make: ***
[/home/abul/works/libjingle/trunk/android/voice-client-core/obj/default_debug/local/armeabi/objs-debug/jingle/talk/base/libdbusglibsymboltable.o]
Error 1
make: *** Waiting for unfinished jobs....
Fatal error: invalid -march= option:`armv5te'
make: ***
[/home/abul/works/libjingle/trunk/android/voice-client-core/obj/default_debug/local/armeabi/objs-debug/jingle/talk/base/dbus.o]
Error 1
Assembler messages:
Fatal error: invalid -march= option: `armv5te'
make: ***
[/home/abul/works/libjingle/trunk/android/voice-client-core/obj/default_debug/local/armeabi/objs-debug/jingle/talk/base/linux.o]
Error 1
make: Leaving directory
`/home/abul/works/libjingle/trunk/android/voice-client-core'

Thanks

**Comment by lukeweber** [comment]
someone commented that they had extracted it incorrectly on their linux
box. Did you drag and drop your ndk, or use tar on the cmd line?

**Comment by walidsynclio** [comment]
I have downloaded it from developer.google.com
just for a check I have even deleted ndk and downloaded and extracted a
fresh copy, but same thing.
I have been trying to build this from a long time, tried different machines
but never had a good luck.

**Comment by lukeweber** [comment]
You didn't say how you extracted it, which was the key point. Use tar directly on the command line and let me know.

Original source for the solution that Max provided, that worked for him:

https://groups.google.com/forum/?fromgroups=#!searchin/webrtc-jingle/I$20guess$20I$20had$20corrupted$20NDK/webrtc-jingle/Bm4E5oefjeE/oxNC127RGeMJ

**Comment by walidsynclio** [comment]
I have extracted by ubuntu gui right click extract.

do you mean I have to use tar directely in path

export ANDROID_NDK_ROOT=/path/to/ndk.tar

or
export ANDROID_NDK_ROOT=/path/to/ndk extracted

actually today I have sync freshly in new directory and run
./tools/badit_android.py
which stops with Error

I dont if I am doing it rightly but I can not see
android/voice-client-example/src/main/java/com/tuenti/voice/example/ui/LoginView.java.

I have followed your descriptions as in Readme file.

**Comment by jreyes** [comment]
in the directory where .gclient and trunk resides, run "gclient sync" 2 times.

Lately been having a trouble where it doesn't sync completely but running the command once more it fixes that.

**Comment by walidsynclio** [comment]
Thanks for your reply
I have tried gclient sync 2 times
Still nothing changed:
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @
voice-core ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.14:test (default-test) @ voice-core ---
[INFO] No tests to run.
[INFO]

## [INFO] --- android-maven-plugin:3.5.1:ndk-build (executeNdk) @ voice-core

[INFO] executing 1 parallel jobs
[INFO] /home/abul/Downloads/android-ndk-r8e/ndk-build [-C,
/home/abul/works/libjingle1/trunk/android/voice-client-core,
NDK_APPLICATION_MK=jni/default_debug.mk, -j, 1,
NDK_APP_OUT=/home/abul/works/libjingle1/trunk/android/voice-client-core/obj/default_debug,
all]
[INFO] Assembler messages:
[INFO] Fatal error: invalid -march= option: `armv5te'
[INFO] make: ***
[/home/abul/works/libjingle1/trunk/android/voice-client-core/obj/default_debug/local/armeabi/objs-debug/jingle_media_unittest/talk/media/base/codec_unittest.o]
Error 1
[ERROR] Error while executing: ANDROID-040-001: Could not execute: Command
= /bin/sh -c cd /home/abul/works/libjingle1/trunk/android/voice-client-core
&& /home/abul/Downloads/android-ndk-r8e/ndk-build -C
/home/abul/works/libjingle1/trunk/android/voice-client-core
NDK_APPLICATION_MK=jni/default_debug.mk -j 1
NDK_APP_OUT=/home/abul/works/libjingle1/trunk/android/voice-client-core/obj/default_debug
all, Result = 2

## [INFO]

[INFO] Reactor Summary:
[INFO]
[INFO] Tuenti Voice Client Parent ........................ SUCCESS [0.849s]
[INFO] Tuenti Voice Client Core .......................... FAILURE [45.081s]
[INFO] Tuenti Voice Client AIDL .......................... SKIPPED
[INFO] Tuenti Voice Client Example ....................... SKIPPED

## [INFO]

[INFO] BUILD FAILURE

## [INFO]

[INFO] Total time: 51.635s
[INFO] Finished at: Sat Apr 06 00:49:10 IST 2013
[INFO] Final Memory: 17M/42M

## [INFO]

[ERROR] Failed to execute goal
com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.5.1:ndk-build
(executeNdk) on project voice-core: ANDROID-040-001: Could not execute:
Command = /bin/sh -c cd
/home/abul/works/libjingle1/trunk/android/voice-client-core &&
/home/abul/Downloads/android-ndk-r8e/ndk-build -C
/home/abul/works/libjingle1/trunk/android/voice-client-core
NDK_APPLICATION_MK=jni/default_debug.mk -j 1
NDK_APP_OUT=/home/abul/works/libjingle1/trunk/android/voice-client-core/obj/default_debug
all, Result = 2 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e
switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions,
please read the following articles:
[ERROR] [Help 1]
http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the
command
[ERROR]   mvn <goals> -rf :voice-core
ERROR:**main**:[KO] Build = mvn install --activate-profiles default_debug

Thanks

**Comment by jreyes** [comment]
hmm, what version of ndk did you installed, the 64 bit? If so, have you tried installing the 32 bit?

**Comment by walidsynclio** [comment]
OS: Ubuntu 64 bit
NDK Linux 64 bit

will I be able to use 32 ndk on 64 bit machine ?
I have never tried it before.
anyway I am downloading 32 bit ndk to give it a shot.

Thanks

**Comment by walidsynclio** [comment]
Thank you all !
finally today I am able to build this with no error and tried it.

even after getting fix for ndk r8e compilation broke because of less memory
in my virtual machine.
after google for a while I increased my virtual machine memory to 2 GB and
it got compiled with no error.

Thanks

**Comment by jreyes** [comment]
Ok, so you got it to compile with the 32 bit version right?

Luke, maybe change the Readme to reflect this, plus add the comment that you need at least 2GB of memory.

**Comment by walidsynclio** [comment]
32 bit ndk will not work on 64 bit ubuntu, I tried it.
I got it to work with 64 bit ndk on a 64 bit ubuntu.

**Comment by lukeweber** [comment]
You tried and installed ia32 libs?

**Comment by walidsynclio** [comment]
yes I have use apt-get and installed ia32 libs.

I have import into eclipse. in project ViEAutotest. its looking for two jar
files
VoiceEngine_android_java.jar
VideoEngine_android_java.jar

Where do I find these. I want to use webrtc voice engine.
Please help

Thank you

**Comment by walidsynclio** [comment]
Hi Luke,
Can you please tell me.
Where is the exact place you are integrating jingle with webrtc.
I want to know the point after signalling you will be passing over the
negotiated IP and port of the called party and local port to webrtc for
media streaming and receiving media from other party.
And other configuration that you need to set in webrtc as per media
negotiation like codec etc.

Thanks for all your help
Abul Walid

**Comment by lukeweber** [comment]
I've added information for windows users in the readme. If any windows users have any tips or requirements to add, please modify the readme and send a pull request. This particular ticket has outlived it's usefulness. Please post on the discussion group if you have further questions.

**Comment by twoh** [comment]
Hi Luke, where is the VideoEngine_android_java.jar located? Thanks
