### ISSUE TITLE
need help for iOS and ANDROID 

### ISSUE THREAD

**Issue by saravanandhandapani** [lukeweber/webrtc-jingle-client#76]
i tried to compile for ios and android, 
1.iOS:
i build it successfully , but when i was trying to run the app getting some exceptions in VoEExternalMediaImpl.h=> private field "playout_delay_ms_" is not used & SessionSendTask.  => private field "timed_out_" is not used

and also one more exception:
Undefined symbols for architecture i386:
  "buzz::XmppRosterModule::Create()", referenced from:
      tuenti::ClientSignalingThread::InitPresence() in clientsignalingthread.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
1. ANDROID:
   build fails,
   it ask for android-ndk r8d or r8, but we can only download latest ndk r8e, there is no way to download the older ndk.
   Please suggestion me where can i make the change to use ndk r8e.

**Comment by lukeweber** [comment]
Change the link to download the correct ndk on Google. I'm willing to try
the new ndk but haven't tested it out yet. If you want to test it,
recommend cleaning voice-client-core/obj and then just add it as an allowed
ndk to the build script. Usually Google breaks something minor but
sometimes it works.

I'm going to try to update the repos and readmes  today and will test all
the code.

**Comment by jreyes** [comment]
You can download 8d from here:

http://dl.google.com/android/ndk/android-ndk-r8d-windows.zip

Also please post issues like this in the mailing list, where people subscribed to the mailing list gets an email about it and also servers as a reference to other people that might have the same problem.

https://groups.google.com/forum/?fromgroups=#!forum/webrtc-jingle

**Comment by lukeweber** [comment]
I just tested out r8e. It seems to generally work, but for whatever reason
the linker on r8d discards icf=safe for mips, as it should I think and on
r8e it fails. You'll notice in default_final.mk I have a check around mips
for this case. It doesn't actually seem to work because that file isn't
called for each arch, but only once, so in this case it fails on the new
ndk for the final build.

**Comment by saravanandhandapani** [comment]
ANDROID:
please tell where extactly i have to make change in build script so that
r8e works without any errors for armeab- v7a archi

IOS:
what about ios?

On Fri, Mar 29, 2013 at 12:38 PM, Luke Weber notifications@github.comwrote:

> I just tested out r8e. It seems to generally work, but for whatever reason
> the linker on r8d discards icf=safe for mips, as it should I think and on
> r8e it fails. You'll notice in default_final.mk I have a check around
> mips
> for this case. It doesn't actually seem to work because that file isn't
> called for each arch, but only once, so in this case it fails on the new
> ndk for the final build.
> 
> On Thu, Mar 28, 2013 at 12:40 PM, saravanandhandapani <
> notifications@github.com> wrote:
> 
> > i tried to compile for ios and android,
> > 1.iOS:
> > i build it successfully , but when i was trying to run the app getting
> > some exceptions in VoEExternalMediaImpl.h=> private field
> > "playout_delay_ms_" is not used & SessionSendTask. => private field
> > "timed_out_" is not used
> > 
> > and also one more exception:
> > Undefined symbols for architecture i386:
> > "buzz::XmppRosterModule::Create()", referenced from:
> > tuenti::ClientSignalingThread::InitPresence() in clientsignalingthread.o
> > ld: symbol(s) not found for architecture i386
> > clang: error: linker command failed with exit code 1 (use -v to see
> > invocation)
> > 1. ANDROID: build fails, it ask for android-ndk r8d or r8, but we can
> >    only download latest ndk r8e, there is no way to download the older ndk.
> >    Please suggestion me where can i make the change to use ndk r8e.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/lukeweber/webrtc-jingle-client/issues/76>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lukeweber/webrtc-jingle-client/issues/76#issuecomment-15631019
> .

## 

Thanks,
_SaRaVaNaN D - SYNCLIO TEAM_

**Comment by lukeweber** [comment]
Don't build for mips or remove the -Wl,--icu=safe from all application level makes, ... voice-client-core/jni/*.mk

IOS:
run gclient sync and follow the instructions in README and let me know if it works now.

**Comment by saravanandhandapani** [comment]
hi,
IOS:
I compiled and run successfully. In phone ui i can see three 1.init 2.
login 3. call

this are the logs for the button action.
step1.init step2.login step3. call ( crashed)

Please tell me whats going wrong?
---------FOR INIT---------

initinitingVoiceClient::
VoiceClient - new ClientSignalingThread client_signaling_thread_@(0x0)
ClientSignalingThread::ClientSignalingThread

--------FOR LOGIN---------

logging in-----Login()VoiceClient::Login
LOGT [stun=(stun.l.google.com:19302),turn=()]
ClientSignalingThread::Login
ClientSignalingThread::OnMessage: MSG_LOGIN
ClientSignalingThread::LoginS
TXmppPump::TXmppPump
TXmppPump::DoLogin
TXmppPump::DoLogin - logging on
ClientSignalingThread::OnMessage: MSG_XMPP_STATE
Resolving addr in PhysicalSocket::Connect
OpenSSLAdapter::OnConnectEvent
ClientSignalingThread::OnMessage: MSG_XMPP_STATE

-------FOR CALL---------

calling-----Call()VoiceClient::Call
ClientSignalingThread::Call
ClientSignalingThread::OnMessage: MSG_CALL
ClientSignalingThread::CallS
Error(common.cc:67): third_party/libjingle/talk/base/scoped_ptr.h(76):
ASSERT FAILED: ptr != NULL @ operator->
(lldb)

On Fri, Mar 29, 2013 at 9:12 PM, Luke Weber notifications@github.comwrote:

> Don't build for mips or remove the -Wl,--icu=safe from all application
> level makes, ... voice-client-core/jni/*.mk
> 
> IOS:
> run gclient sync and follow the instructions in README and let me know if
> it works now.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lukeweber/webrtc-jingle-client/issues/76#issuecomment-15646513
> .

## 

Thanks,
_SaRaVaNaN D - SYNCLIO TEAM_

**Comment by lukeweber** [comment]
Do you wait to fully log in before you hit call?

There's no queuing of any kind on these requests. If you hit button after
button, you'll cause a crash, as roster which is in call requires an
onconnected event for xmpp.

**Comment by saravanandhandapani** [comment]
i tried that too, but no luck..i guess there is a problem in login

On Tue, Apr 9, 2013 at 9:37 PM, Luke Weber notifications@github.com wrote:

> Do you wait to fully log in before you hit call?
> 
> There's no queuing of any kind on these requests. If you hit button after
> button, you'll cause a crash, as roster which is in call requires an
> onconnected event for xmpp.
> 
> On Tue, Apr 9, 2013 at 4:04 PM, saravanandhandapani <
> notifications@github.com> wrote:
> 
> > hi,
> > IOS:
> > I compiled and run successfully. In phone ui i can see three 1.init 2.
> > login 3. call
> > 
> > this are the logs for the button action.
> > step1.init step2.login step3. call ( crashed)
> > 
> > Please tell me whats going wrong?
> > ---------FOR INIT---------
> > 
> > initinitingVoiceClient::
> > VoiceClient - new ClientSignalingThread client_signaling_thread_@(0x0)
> > ClientSignalingThread::ClientSignalingThread
> > 
> > --------FOR LOGIN---------
> > 
> > logging in-----Login()VoiceClient::Login
> > LOGT [stun=(stun.l.google.com:19302),turn=()]
> > ClientSignalingThread::Login
> > ClientSignalingThread::OnMessage: MSG_LOGIN
> > ClientSignalingThread::LoginS
> > TXmppPump::TXmppPump
> > TXmppPump::DoLogin
> > TXmppPump::DoLogin - logging on
> > ClientSignalingThread::OnMessage: MSG_XMPP_STATE
> > Resolving addr in PhysicalSocket::Connect
> > OpenSSLAdapter::OnConnectEvent
> > ClientSignalingThread::OnMessage: MSG_XMPP_STATE
> > 
> > -------FOR CALL---------
> > 
> > calling-----Call()VoiceClient::Call
> > ClientSignalingThread::Call
> > ClientSignalingThread::OnMessage: MSG_CALL
> > ClientSignalingThread::CallS
> > Error(common.cc:67): third_party/libjingle/talk/base/scoped_ptr.h(76):
> > ASSERT FAILED: ptr != NULL @ operator->
> > (lldb)
> > 
> > On Fri, Mar 29, 2013 at 9:12 PM, Luke Weber notifications@github.comwrote:
> > 
> > > Don't build for mips or remove the -Wl,--icu=safe from all application
> > > level makes, ... voice-client-core/jni/*.mk
> > > 
> > > IOS:
> > > run gclient sync and follow the instructions in README and let me know
> > > if
> > > it works now.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/lukeweber/webrtc-jingle-client/issues/76#issuecomment-15646513>
> > 
> > > .
> > 
> > ## 
> > 
> > Thanks,
> > _SaRaVaNaN D - SYNCLIO TEAM_
> > 
> > —
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/lukeweber/webrtc-jingle-client/issues/76#issuecomment-16114178>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lukeweber/webrtc-jingle-client/issues/76#issuecomment-16122535
> .

## 

Thanks,
_SaRaVaNaN D - SYNCLIO TEAM_

**Comment by lukeweber** [comment]
Sorry too many threads about this. You need to disable IOS_XMPP_FRAMEWORK
probably in libjingle.

I've reverted the change for now and pushed. If you gclient sync and then
build again, login should work for you.

Luke
