### ISSUE TITLE
Create a true apk api build

### ISSUE THREAD

**Issue by lukeweber** [lukeweber/webrtc-jingle-client#8]
No UI, just simple programming interface to access this project inside of another app.

**Comment by jreyes** [comment]
There is 2 ways to do this i believe, build 2 dependencies: a .so and .jar dependencies or a apklib dependency. I would be inclined for the apklib dependency since this is an android project. Please add feedback which way to go.

**Comment by lukeweber** [comment]
I'm really open to whatever works best. At the moment it's unknown territory to me and would be happy to go with the best solution. 

apklib sounds right, just don't know if this has any drawbacks.

**Comment by jreyes** [comment]
ok, as I see it, in the java side we would need two projects, the com.tuenti.voice.core project for just the .so and core java files and com.tuenti.voice.example for the UI example implementation unless the UI is no longer needed.

**Comment by lukeweber** [comment]
As well, we should have the com.tuenti.voice.example use the apkl

Some description about how to create them is here.

http://developer.android.com/tools/projects/projects-cmdline.html

**Comment by lukeweber** [comment]
We have a first version of this now building in trunk, so I'm closing, but I'll add a ticket to document the apklib in the wiki at a later stage.
