### ISSUE TITLE
Assembler Error

### ISSUE THREAD

**Issue by walidsynclio** [lukeweber/webrtc-jingle-client#86]
I am building this on 
Ubuntu 64 bit
android-ndk-r8e
latest android sdk

when I run ./tools/badit_android.py

I get this Error
[INFO] --- maven-surefire-plugin:2.14:test (default-test) @ voice-core ---
[INFO] No tests to run.
[INFO] 
[INFO] --- android-maven-plugin:3.5.1:ndk-build (executeNdk) @ voice-core ---
[INFO] Creating native output directory /home/abul/works/libjingle1/trunk/android/voice-client-core/obj/local/armeabi
[INFO] executing 1 parallel jobs
[INFO] /home/abul/Downloads/android-ndk-r8e/ndk-build [-C, /home/abul/works/libjingle1/trunk/android/voice-client-core, NDK_APPLICATION_MK=jni/default_debug.mk, -j, 1, NDK_APP_OUT=/home/abul/works/libjingle1/trunk/android/voice-client-core/obj/default_debug, all]
[INFO] Assembler messages:
[INFO] Fatal error: invalid -march= option: `armv5te'
[INFO] make: **\* [/home/abul/works/libjingle1/trunk/android/voice-client-core/obj/default_debug/local/armeabi/objs-debug/jingle_media_unittest/talk/media/base/codec_unittest.o] Error 1
[ERROR] Error while executing: ANDROID-040-001: Could not execute: Command = /bin/sh -c cd /home/abul/works/libjingle1/trunk/android/voice-client-core && /home/abul/Downloads/android-ndk-r8e/ndk-build -C /home/abul/works/libjingle1/trunk/android/voice-client-core NDK_APPLICATION_MK=jni/default_debug.mk -j 1 NDK_APP_OUT=/home/abul/works/libjingle1/trunk/android/voice-client-core/obj/default_debug all, Result = 2
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Tuenti Voice Client Parent ........................ SUCCESS [0.605s]
[INFO] Tuenti Voice Client Core .......................... FAILURE [22.136s]
[INFO] Tuenti Voice Client AIDL .......................... SKIPPED
[INFO] Tuenti Voice Client Example ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27.962s
[INFO] Finished at: Fri Apr 05 21:38:05 IST 2013
[INFO] Final Memory: 16M/40M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.5.1:ndk-build (executeNdk) on project voice-core: ANDROID-040-001: Could not execute: Command = /bin/sh -c cd /home/abul/works/libjingle1/trunk/android/voice-client-core && /home/abul/Downloads/android-ndk-r8e/ndk-build -C /home/abul/works/libjingle1/trunk/android/voice-client-core NDK_APPLICATION_MK=jni/default_debug.mk -j 1 NDK_APP_OUT=/home/abul/works/libjingle1/trunk/android/voice-client-core/obj/default_debug all, Result = 2 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :voice-core
ERROR:**main**:[KO] Build = mvn install --activate-profiles default_debug

Thanks

**Comment by lukeweber** [comment]
Please don't duplicate tickets.

https://github.com/lukeweber/webrtc-jingle-client/issues/75
