### ISSUE TITLE
Updating projects from gyp files...

### ISSUE THREAD

**Issue by lilu-leo** [lukeweber/webrtc-jingle-client#89]
i perform 
# gclient config https://github.com/lukeweber/webrtc-jingle-client.git --name trunk
# gclient sync

in terminal,

9>create a new branch for your work.
Syncing projects:  96% (30/31), done.third_party/icu      

________ running '/usr/bin/python trunk/tools/create_supplement_gypi.py trunk/client/supplement.gypi' in '/home/leo/webrtcjingleproject'

________ running '/usr/bin/python trunk/build/gyp_chromium --depth=trunk trunk/webrtcjingle.gyp' in '/home/leo/webrtcjingleproject'
Updating projects from gyp files...

When perform at this ,  it break out .then i can not find the 
android/voice-client-example/src/main/java/com/tuenti/voice/example/ui/LoginView.java 
and then i do cd trunk/android/voice-client-core && ./build.sh

Android NDK: Could not find application project directory !  
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.  
make: Entering directory `/home/leo/webrtcjingleproject/trunk/android/voice-client-core'
/home/leo/android-ndk-r8e/build/core/build-local.mk:130: *** Android NDK: Aborting    .  Stop.
make: Leaving directory`/home/leo/webrtcjingleproject/trunk/android/voice-client-core'

in voice-client-core there is not AndroidManifest.xml, i download the zip file,and copy the folder android to  replace the folder android get by gclient sync,

after that   ./build.sh

then find this error:

 jni/voiceclient_main.cc -o /home/leo/webrtcjingleproject/trunk/android/voice-client-core/obj/default_debug/local/armeabi/objs-debug/voiceclient/voiceclient_main.o 
jni/voiceclient_main.cc:36:28: fatal error: client/helpers.h: No such file or directory
compilation terminated.

can you tell me how to solve the problem. thank you.

**Comment by lukeweber** [comment]
Try again. I've updated the readme.

You no longer need to modify the java code with your users as it's in the UI.
Also the build.sh is located in voice-client-native.
As well I've updated the readme to reflect that you should actually by default first try mvn install or tools/badit_android.sh.

Changeset: https://github.com/lukeweber/webrtc-jingle-client/commit/f1a16bf947c9e16461c30a371d2c6a529e9f6a94
