### ISSUE TITLE
what is the RFC Turn Host and username password and Relay Host.

### ISSUE THREAD

**Issue by lilu-leo** [lukeweber/webrtc-jingle-client#90]
i Build the apk:voice-example-1.0-SNAPSHOT.apk and install to a android phone,click the add account,and fill in the username and the password ,but i don't know what is the RFC Turn Host and username password and Relay Host. and not fill in those EditText,and i click the Login button, it do noting ,so need i create a RFC server? and register a username?Thank you,and thanks for you reply yesterday.

**Comment by lukeweber** [comment]
If you haven't installed a turn server, then you simply don't have one,
just leave it blank.

Note though, this means that you won't have a fallback in case your p2p
connection can't be established.

If you call gmail though from the app, it will use your peer's gmail turn
server that gmail provides inside their client in the browser.

Luke
